services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: mysql://root:Tarun#4060@localhost:3306/pilot_tech_submission_form
    depends_on:
      - db
  db:
    image: 3f1574459ddb90933f434abf05ba42324208886bbaa990766fc89491c1ad4bae
    environment:
      MYSQL_ROOT_PASSWORD: Tarun#4060
      MYSQL_DATABASE: pilot_tech_submission_form
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: